In [170]:
import pandas as pd
import numpy as ny

# Importing Dataset

In [171]:
df = pd.read_csv('adult.data') 
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [241]:
df.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

In [146]:
print(x)

[[50 ' Self-emp-not-inc' 83311 ... 0 13 ' United-States']
 [38 ' Private' 215646 ... 0 40 ' United-States']
 [53 ' Private' 234721 ... 0 40 ' United-States']
 ...
 [58 ' Private' 151910 ... 0 40 ' United-States']
 [22 ' Private' 201490 ... 0 20 ' United-States']
 [52 ' Self-emp-inc' 287927 ... 0 40 ' United-States']]


In [147]:
print(y)

[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' <=50K' ' >50K']


# data preprocessing

In [172]:
from sklearn.impute import SimpleImputer
impu = SimpleImputer(missing_values=ny.nan, strategy='most_frequent')
impu.fit(x[:,1:])
x[:,1:] = impu.transform(x[:,1:])

# label Encoding

In [173]:
from sklearn.preprocessing import LabelEncoder
l1 = LabelEncoder()
l3 = LabelEncoder()
l5 = LabelEncoder()
l6 = LabelEncoder()
l7 = LabelEncoder()
l8 = LabelEncoder()
l9 = LabelEncoder()
l13 = LabelEncoder()
x[:,1] = l1.fit_transform(x[:,1])
x[:,3] = l3.fit_transform(x[:,3])
x[:,5] = l5.fit_transform(x[:,5])
x[:,6] = l6.fit_transform(x[:,6])
x[:,7] = l7.fit_transform(x[:,7])
x[:,8] = l8.fit_transform(x[:,8])
x[:,9] = l9.fit_transform(x[:,9])
x[:,13] = l13.fit_transform(x[:,13])
le = LabelEncoder()
y= le.fit_transform(y)

In [174]:
print(x)
print(y)

[[50 6 83311 ... 0 13 39]
 [38 4 215646 ... 0 40 39]
 [53 4 234721 ... 0 40 39]
 ...
 [58 4 151910 ... 0 40 39]
 [22 4 201490 ... 0 20 39]
 [52 5 287927 ... 0 40 39]]
[0 0 0 ... 0 0 1]


# splitting dataset into training  and test set

In [175]:

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [176]:
print(X_test)
print(Y_test)

[[40 5 193524 ... 0 40 39]
 [46 4 188027 ... 0 45 39]
 [33 0 202498 ... 0 40 13]
 ...
 [67 0 192916 ... 0 11 39]
 [24 4 34446 ... 0 37 39]
 [53 4 257940 ... 0 40 39]]
[1 0 0 ... 0 0 0]


# feature scaling

#from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
print(X_train)

In [210]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
print(X_train)

[[-0.33628468  0.09127551 -0.69315211 ... -0.21734867  1.99590813
   0.29260475]
 [ 1.13272256  1.46399178 -0.76998826 ... -0.21734867  0.77463545
   0.29260475]
 [-0.26283431  0.09127551  0.07949564 ... -0.21734867  1.10030817
   0.29260475]
 ...
 [ 0.32476858  1.46399178  1.16037777 ... -0.21734867 -0.85372811
   0.29260475]
 [-1.29113938  2.15034991 -1.44140287 ... -0.21734867  0.77463545
   0.29260475]
 [ 0.76547075  0.77763364 -0.76719457 ... -0.21734867 -0.69089176
   0.29260475]]


In [211]:
print(X_test)

[[ 0.10226245  0.77448414  0.03821724 ... -0.2139029  -0.01939813
   0.28745442]
 [ 0.53884445  0.08548951 -0.01195668 ... -0.2139029   0.37733754
   0.28745442]
 [-0.40708322 -2.67048904  0.1201275  ... -0.2139029  -0.01939813
  -3.03356114]
 ...
 [ 2.06688145 -2.67048904  0.03266771 ... -0.2139029  -2.32046503
   0.28745442]
 [-1.06195621  0.08548951 -1.41376862 ... -0.2139029  -0.25743954
   0.28745442]
 [ 1.04819011  0.08548951  0.62617485 ... -0.2139029  -0.01939813
   0.28745442]]


# training Dataset using Xgboost

In [179]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train,Y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [180]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [247]:
y_pred = classifier.predict(X_test)
cm = confusion_matrix(Y_test,y_pred)
print("accuracy of model\n",accuracy_score(Y_test,y_pred))

accuracy of model
 0.851965601965602


In [249]:
print(cm)

[[4595  362]
 [ 602  953]]


In [253]:
y_trainxg = classifier.predict(X_train)
print("training\n", accuracy_score(Y_train,y_trainxg))

training
 0.9064419533169533


# training Dataset using logistic regrssion

In [226]:
 from sklearn.linear_model import LogisticRegression
reg = LogisticRegression()
reg.fit(X_train,Y_train)


LogisticRegression()

In [245]:
y_prediction = reg.predict(X_test)
y_trains = reg.predict(X_train)
print("accuracy of model\n",accuracy_score(Y_test, y_prediction, normalize = True, sample_weight = None))

accuracy of model
 0.8249385749385749


In [252]:
print("training score\n",accuracy_score(Y_train,y_trains, normalize = True, sample_weight = None))

training score
 0.8249769656019657


In [164]:
reg.predict(X_train)
print(reg.predict([[0,0,0,0,1,4,1,12,12,3,1,2,3,3]]))

[0.52473938]


# Using decison tree

In [237]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(max_depth = 10)
clf.fit(X_train,Y_train)

DecisionTreeClassifier(max_depth=10)

In [238]:
y_preddt = clf.predict(X_test)
y_tsdt = clf.predict(X_train)

In [240]:
print("accuracy of model\n", accuracy_score(Y_test, y_preddt))
print("training accuracy",accuracy_score(Y_train,y_tsdt))

accuracy of model
 0.8499692874692875
training accuracy 0.871007371007371


In [144]:
y1 = clf.predict(X_train)
print(clf.predict([[0,0,0,0,1,4,1,12,12,3,1,2,3,3]]))

[1]
